/**
 * 一些公共的常用到的常量
 */
/** 固定的友链 */
export const friendLinkList = [
    {
        name:"站搜搜",
        url:"https://www.zhansousou.com/",
        iconUrl:'1312312',
    },
    {
        name:"独立开发者",
        url:"https://w2solo.com/",
        iconUrl:'1312312',
    },
    {
        name:"什么值得读",
        url:"http://www.shenmezhidedu.com/",
        iconUrl:'1312312',
    },
    {
        name:"学渣新媒体导航",
        url:"https://www.xuezha.cn/",
        iconUrl:'1312312',
    },
    {
        name:"黑点导航",
        url:"https://www.ihddh.com/",
        iconUrl:'1312312',
    },
    {
        name:"燕十三",
        url:"https://www.yanshisan.cn/",
        iconUrl:'1312312',
    },
    {
        name:"毒蘑菇配色",
        url:"https://color.dumogu.top/",
        iconUrl:'1312312',
    },
    {
        name:"松鼠云办公",
        url:"https://songshu.pro/",
        iconUrl:'1312312',
    },
    {
        name:"帮帮",
        url:"https://www.soubangbang.com/",
        iconUrl:'1312312',
    },
    {
        name:"阅读链",
        url:"https://www.yuedu.pro/",
        iconUrl:'1312312',
    },
    {
        name:"理想青年实验室",
        url:"http://lxqnsys.com/",
        iconUrl:'1312312',
    },
    {
        name:"小呆导航",
        url:"https://webjike.com",
        iconUrl:'1312312',
    },
    {
        name:"24k导航",
        url:"https://www.24kdh.com",
        iconUrl:'1312312',
    },
    {
        name:"一篇文字APP",
        url:"https://www.dumogu.top/bloginfo/1131db71cc",
        iconUrl:'1312312',
    },
    {
        name:"不死鸟",
        url:"https://lai.yuweining.cn/",
        iconUrl:'1312312',
    },
    {
        name:"阿酷导航",
        url:"https://www.a.cool/",
        iconUrl:'1312312',
    },
    {
        name:"笔点",
        url:"https://www.bidianer.com/",
        iconUrl:'https://img.bidianer.com/image/logo/logo.png',
    },
    {
        name:"AcgTab",
        url:"https://acgtab.com/",
        iconUrl:'1312312',
    },
    {
        name:"拓扑导航",
        url:"https://on.the.top/",
        iconUrl:'1312312',
    },
    {
        name:"JOY127乐链网",
        url:"https://www.joy127.com/",
        iconUrl:'1312312',
    },
    {
        name:"只读",
        url:"http://www.rdonly.com/",
        iconUrl:'1312312',
    },
    {
        name:"筑益导航",
        url:"https://nav.zhu-yi.net/",
        iconUrl:'1312312',
    },
    {
        name:"龙猫网",
        url:"https://ailongmiao.com/",
        iconUrl:'1312312',
    },
    {
        name:"创造者日报",
        url:"https://creatorsdaily.com/",
        iconUrl:'1312312',
    },
    {
        name:"林熊熊的小站",
        url:"http://www.linxiongxiong.com/",
        iconUrl:'1312312',
    },
    {
        name:"努力向前",
        url:"https://greatiga.cn/",
        iconUrl:'1312312',
    },
    {
        name:"前端变量管理-毒蘑菇",
        url:"https://var.dumogu.top/",
        iconUrl:'https://dumogu.oss-cn-chengdu.aliyuncs.com/favicon.ico',
    },
    {
        name:"前端变量管理",
        url:"https://web-vars.top/",
        iconUrl:'https://yayaluoya.oss-cn-hangzhou.aliyuncs.com/variables-assets/favicon.ico',
    },
];